//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportShopProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike : Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bike()
        {
            this.SpeedsCount = 1;
        }
    
        public Materials Material { get; set; }
        public int MaxWeight { get; set; }
        public int SpeedsCount { get; set; }
    }
}
