//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportShopProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothes : Product
    {
        public string Sizes { get; set; }
        public string Colors { get; set; }
    }
}
